### PR TITLE
Fix 0 player leaderboard bug and enhance maintenance command

### LINKED ISSUE #41: Handle leaderboard failing when there's 0 players in leaderboard

### LINKED ISSUE #42: Make the Maintenance announcement message not Ephemeral

### PR DESCRIPTION
**Pull request by TheOreoTM**
Bot will no longer error out when there are no players in a leaderboard. Instead, it will send an embed like the following:
This resolves #41 
image

Maintenance command now has two new options. Namely, `channel` and `send_message`.
`channel`: The channel to send the maintenance announcement in **(default: current channel)**
`send_message`: Whether to send the message or not **(default: true)**
This resolves #42 
image

### CODE REVIEW

**Comment by TheOreoTM** [comment]
Okay idk why the global stat commit is being included in this PR. lmk if its a problem i can maybe just refork the git repo and make a new pr.

File: src/commands/tcgAdmin/tcgAdmin.ts [hunk 1]
```diff
@@ -171,3 +172,44 @@ export const command: Command<ChatInputCommandInteraction> = {
     }
   },
 };
+
+async function handleMaintenance(interaction: ChatInputCommandInteraction) {
```
Comment (HxHexa) [inline src/commands/tcgAdmin/tcgAdmin.ts:176]: nit. I'd prefer to move this to a separate file rather than have it for tcgAdmin, but we can refactor it later
